import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1782317463852 implements MigrationInterface {
    name = 'InitialSchema1782317463852'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "schools" ("id" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "address" text, "phone" character varying(50), "email" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_95b932e47ac129dd8e23a0db548" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" character varying(20) NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(20) NOT NULL, "periods_per_week" integer NOT NULL, "is_elective" boolean NOT NULL DEFAULT false, "difficulty" integer NOT NULL DEFAULT '5', "grade_level" text array NOT NULL DEFAULT '{}', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_07a82eb883094a6990b914cc15" ON "subjects" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "teachers" ("subject_id" character varying, "id" character varying(20) NOT NULL, "name" character varying(255) NOT NULL, "short_name" character varying(50) NOT NULL, "employee_code" character varying(20) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20), "subject_ids" text array NOT NULL DEFAULT '{}', "subject_names" text array NOT NULL DEFAULT '{}', "grade_level" text array NOT NULL DEFAULT '{}', "max_periods_day" integer NOT NULL DEFAULT '6', "max_periods_week" integer NOT NULL DEFAULT '30', "status" character varying(20) NOT NULL DEFAULT 'active', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "is_class_teacher" boolean NOT NULL DEFAULT false, "class_teacher_class_id" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1882c07aedb478aca672340c82a" UNIQUE ("employee_code"), CONSTRAINT "UQ_7568c49a630907119e4a665c605" UNIQUE ("email"), CONSTRAINT "PK_a8d4f83be3abe4c687b0a0093c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5656d1b6d40765ea6b135b35d4" ON "teachers" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'student', "teacher_id" character varying(20), "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "refresh_token_hash" text, "fcm_token" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6732917f537f13ea6555a8b493" ON "users" ("teacher_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_25e1cf8f41bae2f3d11f3c2a02" ON "users" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "classes" ("id" character varying(20) NOT NULL, "name" character varying(50) NOT NULL, "sections" text array NOT NULL DEFAULT '{}', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_398f3990f5da4a1efda173f576" ON "classes" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" character varying(20) NOT NULL, "name" character varying(100) NOT NULL, "type" character varying(30) NOT NULL DEFAULT 'classroom', "capacity" integer NOT NULL DEFAULT '30', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ffaac60590923112dad474b21d" ON "rooms" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "sections" ("id" character varying(40) NOT NULL, "class_id" character varying(20) NOT NULL, "name" character varying(10) NOT NULL, "class_teacher_id" character varying(20), "room_id" character varying(20), "capacity" integer NOT NULL DEFAULT '40', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_section_class_name" UNIQUE ("class_id", "name"), CONSTRAINT "PK_f9749dd3bffd880a497d007e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff9259b86078bdc799eab2ee8e" ON "sections" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "periods" ("id" character varying(20) NOT NULL, "number" integer NOT NULL, "start_time" character varying(10) NOT NULL, "end_time" character varying(10) NOT NULL, "is_break" boolean NOT NULL DEFAULT false, "label" character varying(50) NOT NULL, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86c6afb6c818d97dc321898627c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc74c222bae152f555afd69b5e" ON "periods" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "academic_years" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "is_active" boolean NOT NULL DEFAULT false, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_645d0f115fa85aaecffdc11cbaa" UNIQUE ("name"), CONSTRAINT "PK_2021b90bfbfa6c9da7df34ca1cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b293eb7909d2a3aae86c438071" ON "academic_years" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "academic_year_id" integer, "title" character varying(255) NOT NULL, "description" text, "created_by" uuid NOT NULL, "created_by_name" character varying(255), "status" character varying NOT NULL DEFAULT 'pending', "priority" character varying(20) NOT NULL DEFAULT 'medium', "start_date" date, "due_date" TIMESTAMP WITH TIME ZONE, "remarks" text, "assigned_to" text array NOT NULL DEFAULT '{}', "file_url" text, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_91edc2ef35ee38f2954c00d884" ON "tasks" ("academic_year_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fc727aef9e222ebd09dc8dac0" ON "tasks" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_da092d55ea8902101546001557" ON "tasks" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "task_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "teacher_id" character varying(20) NOT NULL, "status" character varying NOT NULL DEFAULT 'not_started', "escalated" boolean NOT NULL DEFAULT false, "escalation_count" integer NOT NULL DEFAULT '0', "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b68f42cf36d807d8a19a96066d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b389f4488d0a8241c3c9827396" ON "task_assignments" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_02e8cb2d8b1b9463170e2c306d" ON "task_assignments" ("teacher_id") `);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" character varying(5) NOT NULL, "fullName" character varying(255) NOT NULL, "email" character varying(255), "passwordHash" character varying NOT NULL, "className" character varying(100) NOT NULL, "section" character varying(10) NOT NULL, "section_id" character varying(40), "refresh_token_hash" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9d9f010d4d6a6eea8b4779638c4" UNIQUE ("studentId"), CONSTRAINT "UQ_25985d58c714a4a427ced57507b" UNIQUE ("email"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3e1663d65a2373870a2511d6dc" ON "students" ("section_id") `);
        await queryRunner.query(`CREATE TABLE "leave_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "academic_year_id" integer, "leave_duration" character varying(20) NOT NULL DEFAULT 'FULL_DAY', "deducted_leaves" numeric(4,1) NOT NULL DEFAULT '1', "teacher_id" character varying(20), "student_id" uuid, "leave_owner_type" character varying(10) NOT NULL DEFAULT 'teacher', "leave_type" character varying(20) NOT NULL DEFAULT 'other', "start_date" date NOT NULL, "end_date" date NOT NULL, "reason" text, "status" character varying NOT NULL DEFAULT 'pending', "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "approved_at" TIMESTAMP WITH TIME ZONE, "approved_by" uuid, "remarks" text, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "proxy_assigned" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d986913818cf9a2943d0dbe8f56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7cf62e0854c324a5ccb7513b70" ON "leave_applications" ("academic_year_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2185491535437ea8aac187c132" ON "leave_applications" ("teacher_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff2b89282c3d88c46ee2834c3c" ON "leave_applications" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc32f4c58cad16330763d5d8db" ON "leave_applications" ("approved_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_df1cb565d5a1e9a89edfa9bd89" ON "leave_applications" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "proxy_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "leave_application_id" uuid, "original_teacher_id" character varying(20), "proxy_teacher_id" character varying(20), "class_id" character varying(20) NOT NULL, "subject_id" character varying(20) NOT NULL, "date" date NOT NULL, "period_id" character varying(20), "status" character varying NOT NULL DEFAULT 'pending', "approved_at" TIMESTAMP WITH TIME ZONE, "approved_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2ae21510e7d7d81eda68b1466fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d5bf58d73fc98adce00f3cbc5" ON "proxy_assignments" ("leave_application_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0023da3e5c6886d3f4f96f53f4" ON "proxy_assignments" ("original_teacher_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1e89038cfff19d1e75380bce0" ON "proxy_assignments" ("proxy_teacher_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_073d5e70905092f7e65c1a2132" ON "proxy_assignments" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7d91d2e8befa54858227e5a87" ON "proxy_assignments" ("subject_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_675deb5b87cba913a81198f9ab" ON "proxy_assignments" ("period_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1def42f199c21dc11ed5ff1c17" ON "proxy_assignments" ("approved_by") `);
        await queryRunner.query(`CREATE TABLE "timetables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "academic_year_id" integer, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "grids" jsonb, "published_at" TIMESTAMP WITH TIME ZONE, "effective_from" date, "effective_to" date, "published_by" character varying, "class_id" character varying, "status" character varying(20) NOT NULL DEFAULT 'draft', "is_active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9dd7e50645bff59e9ac5b4725c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba199f123599e28e769f5ee346" ON "timetables" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "timetable_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" character varying(50) NOT NULL, "period_slots" jsonb NOT NULL DEFAULT '[]', "working_days" text array NOT NULL DEFAULT '{}', "rules" jsonb NOT NULL DEFAULT '{}', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e51acb457958c3f13af091b4675" UNIQUE ("school_id"), CONSTRAINT "PK_577d64d1b6d6c37e6daa3d3647d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_records_status_enum" AS ENUM('present', 'absent', 'leave')`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" uuid NOT NULL, "class_id" character varying(20) NOT NULL, "section" character varying(10), "date" date NOT NULL, "status" "public"."attendance_records_status_enum" NOT NULL DEFAULT 'present', "remarks" text, "marked_by_teacher_id" character varying(20), "subject_id" character varying(20), "period_id" character varying(20), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fa3f22fca80ff41e0d318923ea3" UNIQUE ("student_id", "date"), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dbace05c012526710663f8d891" ON "attendance_records" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc48ccbd03396874857ab06ac3" ON "attendance_records" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fb6ef15f899489af7e47b6c83" ON "attendance_records" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_300b711f56401d72f6311f44f9" ON "attendance_records" ("marked_by_teacher_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7b3ea45da711f7031dd32b164" ON "attendance_records" ("subject_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ad047215c958f42bb9ce873d4" ON "attendance_records" ("period_id") `);
        await queryRunner.query(`CREATE TABLE "fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "due_date" date NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'pending', "description" character varying(255), "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_97f3a1b1b8ee5674fd4da93f461" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ad84dd647a6c4464ed46829b2" ON "fees" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_97681df21ec81ea3a54e53e27c" ON "fees" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "academic_year_id" integer, "title" character varying(255) NOT NULL, "type" character varying(50), "data" jsonb, "created_by" uuid NOT NULL, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70373476f7f7e7c911c07bbdb4" ON "reports" ("academic_year_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a20814878638f52ffc91005fc4" ON "reports" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_88654fbe94fbc4b5c432a57adb" ON "reports" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "type" character varying NOT NULL DEFAULT 'task', "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "teacher_leave_balances" ("id" SERIAL NOT NULL, "teacher_id" character varying(20) NOT NULL, "academic_year_id" integer NOT NULL, "total_leaves" numeric(5,1) NOT NULL DEFAULT '20', "used_leaves" numeric(5,1) NOT NULL DEFAULT '0', "remaining_leaves" numeric(5,1) NOT NULL DEFAULT '20', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d10af2b59a563eb94c7318c89b0" UNIQUE ("teacher_id", "academic_year_id"), CONSTRAINT "PK_08bf8eed3880ba6be927d5bf8ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_abff742fbfe44d5592b8672ef2" ON "teacher_leave_balances" ("academic_year_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d0f1e6e87514c11ff13a93a2c" ON "teacher_leave_balances" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "message" text NOT NULL, "type" character varying NOT NULL DEFAULT 'general', "rating" integer, "principal_id" uuid NOT NULL, "teacher_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8389f9e087a57689cd5be8b2b13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "circulars" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text NOT NULL, "category" character varying NOT NULL DEFAULT 'General', "created_by" uuid NOT NULL, "created_by_role" character varying(50) NOT NULL, "is_published" boolean NOT NULL DEFAULT true, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d5986883d52418ff55d9b5834d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_67cb2cd87364e8e8a9ddad03ea" ON "circulars" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_9dadbb0fa7498ccb68937b20a1" ON "circulars" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "mailbox_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "message" text NOT NULL, "sender_name" character varying(255) NOT NULL, "sender_role" character varying(50) NOT NULL, "category" character varying NOT NULL DEFAULT 'General', "is_published" boolean NOT NULL DEFAULT true, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_865e565d761179ce3e394b8b619" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6d7bfb0aac4fb45b156e1e90e1" ON "mailbox_messages" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text NOT NULL, "category" character varying(100) NOT NULL, "level" character varying(100), "badge" character varying(100), "awarded_on" date, "student_id" uuid NOT NULL, "student_ref_id" character varying(20), "student_name" character varying(255) NOT NULL, "class_name" character varying(100), "created_by" character varying(50), "created_by_role" character varying(50), "featured" boolean NOT NULL DEFAULT false, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bc19c37c6249f70186f318d71d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4f0c6065670e5a3d6f53b18ac" ON "achievements" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a1fe9f183800f1cdd06134d4a" ON "achievements" ("school_id") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "sender_id" character varying(50) NOT NULL, "sender_role" character varying(20) NOT NULL, "sender_name" character varying(255) NOT NULL, "receiver_id" character varying(50) NOT NULL, "receiver_role" character varying(20) NOT NULL, "receiver_name" character varying(255) NOT NULL, "subject" character varying(255) NOT NULL, "message" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "deleted_by_sender" boolean NOT NULL DEFAULT false, "deleted_by_receiver" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "homework" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text NOT NULL, "topic" character varying(255), "priority" character varying(20) NOT NULL DEFAULT 'medium', "submission_type" character varying(10) NOT NULL, "class_id" character varying(20) NOT NULL, "class_name" character varying(100) NOT NULL, "subject_id" character varying(20) NOT NULL, "subject_name" character varying(100) NOT NULL, "teacher_id" character varying(20) NOT NULL, "teacher_name" character varying(255) NOT NULL, "academic_year_id" integer NOT NULL, "attachment_url" text, "attachment_name" character varying, "attachment_mime_type" character varying, "attachment_size" integer, "status" character varying(20) NOT NULL DEFAULT 'published', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90dbf463ef94040ed137c4fd38d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e0661a16383ebbc254f3cfa296" ON "homework" ("subject_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eae0937122bb4a5871fc79e3f2" ON "homework" ("academic_year_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f76344805d85ca1f9657da5df" ON "homework" ("school_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f17cbe8bf30586be3044a515e" ON "homework" ("class_id", "subject_id", "academic_year_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e85813c4d383eca4ce4c689a9" ON "homework" ("teacher_id", "academic_year_id") `);
        await queryRunner.query(`CREATE TABLE "homework_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "homework_id" uuid NOT NULL, "section" character varying(10) NOT NULL, "deadline" TIMESTAMP WITH TIME ZONE NOT NULL, "published_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'published', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_26f75ad244f07a4cb7fd87115c0" UNIQUE ("homework_id", "section"), CONSTRAINT "PK_6e96c9e0467aa788a4ce9c81ac5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09acc0227dc8b257606b8b4eb4" ON "homework_assignments" ("homework_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b38d74a247e02df0914f5586b6" ON "homework_assignments" ("section", "deadline") `);
        await queryRunner.query(`CREATE TABLE "homework_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "homework_assignment_id" uuid NOT NULL, "student_id" uuid NOT NULL, "submission_text" text, "file_url" text, "file_name" character varying, "file_mime_type" character varying, "file_size" integer, "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "submission_version" integer NOT NULL DEFAULT '1', "status" character varying(20) NOT NULL DEFAULT 'submitted', "marks_obtained" numeric(6,2), "teacher_feedback" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c100251dd6184d4ddaf1982ad6c" UNIQUE ("homework_assignment_id", "student_id"), CONSTRAINT "PK_4c570ffb4ce1a34b63afa9d1b26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3b2235f48ab8488a9e964c0172" ON "homework_submissions" ("student_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2c5cfd2ad5e3a2c070577a70b" ON "homework_submissions" ("homework_assignment_id") `);
        await queryRunner.query(`CREATE TABLE "teaching_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teacher_id" character varying(20) NOT NULL, "class_id" character varying(20) NOT NULL, "section" character varying(10) NOT NULL, "subject_id" character varying(20) NOT NULL, "academic_year_id" integer NOT NULL, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae367d2dbacbc21d9bb785de4cb" UNIQUE ("teacher_id", "class_id", "section", "subject_id", "academic_year_id"), CONSTRAINT "PK_baf0d10098561a9840957b512e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f706b6623dae17c566e8a579fc" ON "teaching_assignments" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_41ec23a5853e01d7607405c4a8" ON "teaching_assignments" ("subject_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3e771d506c6233ceffe5ae719" ON "teaching_assignments" ("academic_year_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d88d65d9552feb82d5f6e7fe0" ON "teaching_assignments" ("school_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b54511fb475e89f52e8f2c246" ON "teaching_assignments" ("teacher_id", "academic_year_id", "is_active") `);
        await queryRunner.query(`CREATE TABLE "syllabus" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "class_id" character varying(20) NOT NULL, "class_name" character varying(100) NOT NULL, "subject_id" character varying(20) NOT NULL, "subject_name" character varying(100) NOT NULL, "teacher_id" character varying(20) NOT NULL, "teacher_name" character varying(255) NOT NULL, "total_chapters" integer NOT NULL DEFAULT '0', "completed_chapters" integer NOT NULL DEFAULT '0', "completion_percentage" double precision NOT NULL DEFAULT '0', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "academic_year_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5205bdbdb2d719615ccf5eabfb5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_98f18ccb8e3f01f8051ca8ae47" ON "syllabus" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_84076f08bebb15b7ae885440ae" ON "syllabus" ("subject_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_68b267287cfa1c24a23e0f3ad7" ON "syllabus" ("teacher_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_76d1df4a0706f0a9436a532d07" ON "syllabus" ("school_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_09fc57c568167bf8a445d6f09d" ON "syllabus" ("academic_year_id") `);
        await queryRunner.query(`CREATE TABLE "syllabus_chapters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "syllabus_id" uuid NOT NULL, "chapter_name" character varying(255) NOT NULL, "chapter_number" integer NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "completed_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3fa29958a9d3077c1c7512a3960" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1c8750e91d78195d8728e442cb" ON "syllabus_chapters" ("syllabus_id") `);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_07a82eb883094a6990b914cc15e" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_4d8b425eabbf542265e620d6111" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_5656d1b6d40765ea6b135b35d4b" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_6732917f537f13ea6555a8b493e" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_25e1cf8f41bae2f3d11f3c2a028" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_398f3990f5da4a1efda173f576f" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_ffaac60590923112dad474b21dc" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_27db91d7369af6f181412afa99f" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_9e40f861d3aaf51ea6e9ba4b76d" FOREIGN KEY ("class_teacher_id") REFERENCES "teachers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_8cb4031f7556945bc3e155f57ff" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_ff9259b86078bdc799eab2ee8ea" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "periods" ADD CONSTRAINT "FK_bc74c222bae152f555afd69b5ef" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD CONSTRAINT "FK_b293eb7909d2a3aae86c4380713" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_91edc2ef35ee38f2954c00d8842" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_da092d55ea89021015460015574" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_assignments" ADD CONSTRAINT "FK_b389f4488d0a8241c3c98273966" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_assignments" ADD CONSTRAINT "FK_02e8cb2d8b1b9463170e2c306dd" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_3e1663d65a2373870a2511d6dc4" FOREIGN KEY ("section_id") REFERENCES "sections"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_7cf62e0854c324a5ccb7513b70c" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_2185491535437ea8aac187c132b" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_ff2b89282c3d88c46ee2834c3c8" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_fc32f4c58cad16330763d5d8db6" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_df1cb565d5a1e9a89edfa9bd897" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" ADD CONSTRAINT "FK_7d5bf58d73fc98adce00f3cbc56" FOREIGN KEY ("leave_application_id") REFERENCES "leave_applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" ADD CONSTRAINT "FK_0023da3e5c6886d3f4f96f53f43" FOREIGN KEY ("original_teacher_id") REFERENCES "teachers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" ADD CONSTRAINT "FK_d1e89038cfff19d1e75380bce08" FOREIGN KEY ("proxy_teacher_id") REFERENCES "teachers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" ADD CONSTRAINT "FK_073d5e70905092f7e65c1a2132f" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" ADD CONSTRAINT "FK_a7d91d2e8befa54858227e5a87d" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" ADD CONSTRAINT "FK_675deb5b87cba913a81198f9abd" FOREIGN KEY ("period_id") REFERENCES "periods"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" ADD CONSTRAINT "FK_1def42f199c21dc11ed5ff1c170" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetables" ADD CONSTRAINT "FK_ba199f123599e28e769f5ee346e" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_settings" ADD CONSTRAINT "FK_e51acb457958c3f13af091b4675" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_dbace05c012526710663f8d8911" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_cc48ccbd03396874857ab06ac3b" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_300b711f56401d72f6311f44f95" FOREIGN KEY ("marked_by_teacher_id") REFERENCES "teachers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_e7b3ea45da711f7031dd32b1649" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_3ad047215c958f42bb9ce873d44" FOREIGN KEY ("period_id") REFERENCES "periods"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fees" ADD CONSTRAINT "FK_1ad84dd647a6c4464ed46829b25" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fees" ADD CONSTRAINT "FK_97681df21ec81ea3a54e53e27c8" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_70373476f7f7e7c911c07bbdb46" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_a20814878638f52ffc91005fc42" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_88654fbe94fbc4b5c432a57adbd" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_leave_balances" ADD CONSTRAINT "FK_339792a8587cb06bea5ced5941b" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_leave_balances" ADD CONSTRAINT "FK_abff742fbfe44d5592b8672ef2b" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_leave_balances" ADD CONSTRAINT "FK_5d0f1e6e87514c11ff13a93a2cd" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_d849a6bd5722670e6e182f7d00c" FOREIGN KEY ("principal_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_bb612409cbb5c4563d2dad30ade" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circulars" ADD CONSTRAINT "FK_67cb2cd87364e8e8a9ddad03ea2" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circulars" ADD CONSTRAINT "FK_9dadbb0fa7498ccb68937b20a11" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mailbox_messages" ADD CONSTRAINT "FK_6d7bfb0aac4fb45b156e1e90e13" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievements" ADD CONSTRAINT "FK_f4f0c6065670e5a3d6f53b18acb" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievements" ADD CONSTRAINT "FK_5a1fe9f183800f1cdd06134d4af" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework" ADD CONSTRAINT "FK_fd37965791c696be7f9f4f8ec16" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework" ADD CONSTRAINT "FK_e0661a16383ebbc254f3cfa2963" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework" ADD CONSTRAINT "FK_05013feecbe1d61eba2e4cf08cd" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework" ADD CONSTRAINT "FK_eae0937122bb4a5871fc79e3f2c" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework" ADD CONSTRAINT "FK_7f76344805d85ca1f9657da5dfc" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" ADD CONSTRAINT "FK_09acc0227dc8b257606b8b4eb49" FOREIGN KEY ("homework_id") REFERENCES "homework"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" ADD CONSTRAINT "FK_d2c5cfd2ad5e3a2c070577a70b0" FOREIGN KEY ("homework_assignment_id") REFERENCES "homework_assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" ADD CONSTRAINT "FK_1397103587dce2c2320ee2c2f23" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" ADD CONSTRAINT "FK_7eb84b6d68b1db6cc46b5fcea98" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" ADD CONSTRAINT "FK_f706b6623dae17c566e8a579fc0" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" ADD CONSTRAINT "FK_41ec23a5853e01d7607405c4a8e" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" ADD CONSTRAINT "FK_e3e771d506c6233ceffe5ae7192" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" ADD CONSTRAINT "FK_5d88d65d9552feb82d5f6e7fe0e" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus" ADD CONSTRAINT "FK_98f18ccb8e3f01f8051ca8ae477" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus" ADD CONSTRAINT "FK_84076f08bebb15b7ae885440ae3" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus" ADD CONSTRAINT "FK_68b267287cfa1c24a23e0f3ad76" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus" ADD CONSTRAINT "FK_76d1df4a0706f0a9436a532d07a" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus" ADD CONSTRAINT "FK_09fc57c568167bf8a445d6f09df" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_chapters" ADD CONSTRAINT "FK_1c8750e91d78195d8728e442cb3" FOREIGN KEY ("syllabus_id") REFERENCES "syllabus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "syllabus_chapters" DROP CONSTRAINT "FK_1c8750e91d78195d8728e442cb3"`);
        await queryRunner.query(`ALTER TABLE "syllabus" DROP CONSTRAINT "FK_09fc57c568167bf8a445d6f09df"`);
        await queryRunner.query(`ALTER TABLE "syllabus" DROP CONSTRAINT "FK_76d1df4a0706f0a9436a532d07a"`);
        await queryRunner.query(`ALTER TABLE "syllabus" DROP CONSTRAINT "FK_68b267287cfa1c24a23e0f3ad76"`);
        await queryRunner.query(`ALTER TABLE "syllabus" DROP CONSTRAINT "FK_84076f08bebb15b7ae885440ae3"`);
        await queryRunner.query(`ALTER TABLE "syllabus" DROP CONSTRAINT "FK_98f18ccb8e3f01f8051ca8ae477"`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" DROP CONSTRAINT "FK_5d88d65d9552feb82d5f6e7fe0e"`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" DROP CONSTRAINT "FK_e3e771d506c6233ceffe5ae7192"`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" DROP CONSTRAINT "FK_41ec23a5853e01d7607405c4a8e"`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" DROP CONSTRAINT "FK_f706b6623dae17c566e8a579fc0"`);
        await queryRunner.query(`ALTER TABLE "teaching_assignments" DROP CONSTRAINT "FK_7eb84b6d68b1db6cc46b5fcea98"`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" DROP CONSTRAINT "FK_1397103587dce2c2320ee2c2f23"`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" DROP CONSTRAINT "FK_d2c5cfd2ad5e3a2c070577a70b0"`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" DROP CONSTRAINT "FK_09acc0227dc8b257606b8b4eb49"`);
        await queryRunner.query(`ALTER TABLE "homework" DROP CONSTRAINT "FK_7f76344805d85ca1f9657da5dfc"`);
        await queryRunner.query(`ALTER TABLE "homework" DROP CONSTRAINT "FK_eae0937122bb4a5871fc79e3f2c"`);
        await queryRunner.query(`ALTER TABLE "homework" DROP CONSTRAINT "FK_05013feecbe1d61eba2e4cf08cd"`);
        await queryRunner.query(`ALTER TABLE "homework" DROP CONSTRAINT "FK_e0661a16383ebbc254f3cfa2963"`);
        await queryRunner.query(`ALTER TABLE "homework" DROP CONSTRAINT "FK_fd37965791c696be7f9f4f8ec16"`);
        await queryRunner.query(`ALTER TABLE "achievements" DROP CONSTRAINT "FK_5a1fe9f183800f1cdd06134d4af"`);
        await queryRunner.query(`ALTER TABLE "achievements" DROP CONSTRAINT "FK_f4f0c6065670e5a3d6f53b18acb"`);
        await queryRunner.query(`ALTER TABLE "mailbox_messages" DROP CONSTRAINT "FK_6d7bfb0aac4fb45b156e1e90e13"`);
        await queryRunner.query(`ALTER TABLE "circulars" DROP CONSTRAINT "FK_9dadbb0fa7498ccb68937b20a11"`);
        await queryRunner.query(`ALTER TABLE "circulars" DROP CONSTRAINT "FK_67cb2cd87364e8e8a9ddad03ea2"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_bb612409cbb5c4563d2dad30ade"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_d849a6bd5722670e6e182f7d00c"`);
        await queryRunner.query(`ALTER TABLE "teacher_leave_balances" DROP CONSTRAINT "FK_5d0f1e6e87514c11ff13a93a2cd"`);
        await queryRunner.query(`ALTER TABLE "teacher_leave_balances" DROP CONSTRAINT "FK_abff742fbfe44d5592b8672ef2b"`);
        await queryRunner.query(`ALTER TABLE "teacher_leave_balances" DROP CONSTRAINT "FK_339792a8587cb06bea5ced5941b"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_88654fbe94fbc4b5c432a57adbd"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_a20814878638f52ffc91005fc42"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_70373476f7f7e7c911c07bbdb46"`);
        await queryRunner.query(`ALTER TABLE "fees" DROP CONSTRAINT "FK_97681df21ec81ea3a54e53e27c8"`);
        await queryRunner.query(`ALTER TABLE "fees" DROP CONSTRAINT "FK_1ad84dd647a6c4464ed46829b25"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_3ad047215c958f42bb9ce873d44"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_e7b3ea45da711f7031dd32b1649"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_300b711f56401d72f6311f44f95"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_cc48ccbd03396874857ab06ac3b"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_dbace05c012526710663f8d8911"`);
        await queryRunner.query(`ALTER TABLE "timetable_settings" DROP CONSTRAINT "FK_e51acb457958c3f13af091b4675"`);
        await queryRunner.query(`ALTER TABLE "timetables" DROP CONSTRAINT "FK_ba199f123599e28e769f5ee346e"`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" DROP CONSTRAINT "FK_1def42f199c21dc11ed5ff1c170"`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" DROP CONSTRAINT "FK_675deb5b87cba913a81198f9abd"`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" DROP CONSTRAINT "FK_a7d91d2e8befa54858227e5a87d"`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" DROP CONSTRAINT "FK_073d5e70905092f7e65c1a2132f"`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" DROP CONSTRAINT "FK_d1e89038cfff19d1e75380bce08"`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" DROP CONSTRAINT "FK_0023da3e5c6886d3f4f96f53f43"`);
        await queryRunner.query(`ALTER TABLE "proxy_assignments" DROP CONSTRAINT "FK_7d5bf58d73fc98adce00f3cbc56"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_df1cb565d5a1e9a89edfa9bd897"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_fc32f4c58cad16330763d5d8db6"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_ff2b89282c3d88c46ee2834c3c8"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_2185491535437ea8aac187c132b"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_7cf62e0854c324a5ccb7513b70c"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_3e1663d65a2373870a2511d6dc4"`);
        await queryRunner.query(`ALTER TABLE "task_assignments" DROP CONSTRAINT "FK_02e8cb2d8b1b9463170e2c306dd"`);
        await queryRunner.query(`ALTER TABLE "task_assignments" DROP CONSTRAINT "FK_b389f4488d0a8241c3c98273966"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_da092d55ea89021015460015574"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_91edc2ef35ee38f2954c00d8842"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP CONSTRAINT "FK_b293eb7909d2a3aae86c4380713"`);
        await queryRunner.query(`ALTER TABLE "periods" DROP CONSTRAINT "FK_bc74c222bae152f555afd69b5ef"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_ff9259b86078bdc799eab2ee8ea"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_8cb4031f7556945bc3e155f57ff"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_9e40f861d3aaf51ea6e9ba4b76d"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_27db91d7369af6f181412afa99f"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_ffaac60590923112dad474b21dc"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_398f3990f5da4a1efda173f576f"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_25e1cf8f41bae2f3d11f3c2a028"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_6732917f537f13ea6555a8b493e"`);
        await queryRunner.query(`ALTER TABLE "teachers" DROP CONSTRAINT "FK_5656d1b6d40765ea6b135b35d4b"`);
        await queryRunner.query(`ALTER TABLE "teachers" DROP CONSTRAINT "FK_4d8b425eabbf542265e620d6111"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "FK_07a82eb883094a6990b914cc15e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c8750e91d78195d8728e442cb"`);
        await queryRunner.query(`DROP TABLE "syllabus_chapters"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09fc57c568167bf8a445d6f09d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76d1df4a0706f0a9436a532d07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68b267287cfa1c24a23e0f3ad7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84076f08bebb15b7ae885440ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98f18ccb8e3f01f8051ca8ae47"`);
        await queryRunner.query(`DROP TABLE "syllabus"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b54511fb475e89f52e8f2c246"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d88d65d9552feb82d5f6e7fe0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3e771d506c6233ceffe5ae719"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41ec23a5853e01d7607405c4a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f706b6623dae17c566e8a579fc"`);
        await queryRunner.query(`DROP TABLE "teaching_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2c5cfd2ad5e3a2c070577a70b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b2235f48ab8488a9e964c0172"`);
        await queryRunner.query(`DROP TABLE "homework_submissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b38d74a247e02df0914f5586b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09acc0227dc8b257606b8b4eb4"`);
        await queryRunner.query(`DROP TABLE "homework_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e85813c4d383eca4ce4c689a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f17cbe8bf30586be3044a515e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f76344805d85ca1f9657da5df"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eae0937122bb4a5871fc79e3f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0661a16383ebbc254f3cfa296"`);
        await queryRunner.query(`DROP TABLE "homework"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a1fe9f183800f1cdd06134d4a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4f0c6065670e5a3d6f53b18ac"`);
        await queryRunner.query(`DROP TABLE "achievements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d7bfb0aac4fb45b156e1e90e1"`);
        await queryRunner.query(`DROP TABLE "mailbox_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dadbb0fa7498ccb68937b20a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67cb2cd87364e8e8a9ddad03ea"`);
        await queryRunner.query(`DROP TABLE "circulars"`);
        await queryRunner.query(`DROP TABLE "feedback"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d0f1e6e87514c11ff13a93a2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abff742fbfe44d5592b8672ef2"`);
        await queryRunner.query(`DROP TABLE "teacher_leave_balances"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88654fbe94fbc4b5c432a57adb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a20814878638f52ffc91005fc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70373476f7f7e7c911c07bbdb4"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97681df21ec81ea3a54e53e27c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ad84dd647a6c4464ed46829b2"`);
        await queryRunner.query(`DROP TABLE "fees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ad047215c958f42bb9ce873d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7b3ea45da711f7031dd32b164"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_300b711f56401d72f6311f44f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fb6ef15f899489af7e47b6c83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc48ccbd03396874857ab06ac3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbace05c012526710663f8d891"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_records_status_enum"`);
        await queryRunner.query(`DROP TABLE "timetable_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba199f123599e28e769f5ee346"`);
        await queryRunner.query(`DROP TABLE "timetables"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1def42f199c21dc11ed5ff1c17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_675deb5b87cba913a81198f9ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7d91d2e8befa54858227e5a87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_073d5e70905092f7e65c1a2132"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1e89038cfff19d1e75380bce0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0023da3e5c6886d3f4f96f53f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d5bf58d73fc98adce00f3cbc5"`);
        await queryRunner.query(`DROP TABLE "proxy_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df1cb565d5a1e9a89edfa9bd89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc32f4c58cad16330763d5d8db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff2b89282c3d88c46ee2834c3c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2185491535437ea8aac187c132"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cf62e0854c324a5ccb7513b70"`);
        await queryRunner.query(`DROP TABLE "leave_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e1663d65a2373870a2511d6dc"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02e8cb2d8b1b9463170e2c306d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b389f4488d0a8241c3c9827396"`);
        await queryRunner.query(`DROP TABLE "task_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da092d55ea8902101546001557"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fc727aef9e222ebd09dc8dac0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91edc2ef35ee38f2954c00d884"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b293eb7909d2a3aae86c438071"`);
        await queryRunner.query(`DROP TABLE "academic_years"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc74c222bae152f555afd69b5e"`);
        await queryRunner.query(`DROP TABLE "periods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff9259b86078bdc799eab2ee8e"`);
        await queryRunner.query(`DROP TABLE "sections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffaac60590923112dad474b21d"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_398f3990f5da4a1efda173f576"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25e1cf8f41bae2f3d11f3c2a02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6732917f537f13ea6555a8b493"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5656d1b6d40765ea6b135b35d4"`);
        await queryRunner.query(`DROP TABLE "teachers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07a82eb883094a6990b914cc15"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`DROP TABLE "schools"`);
    }

}
