import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1782298456212 implements MigrationInterface {
    name = 'InitialSchema1782298456212'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'student', "teacher_id" character varying(50), "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "refresh_token_hash" text, "fcm_token" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teachers" ("subject_id" character varying, "id" character varying(20) NOT NULL, "name" character varying(255) NOT NULL, "short_name" character varying(50) NOT NULL, "employee_code" character varying(20) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20), "subject_ids" text array NOT NULL DEFAULT '{}', "subject_names" text array NOT NULL DEFAULT '{}', "grade_level" text array NOT NULL DEFAULT '{}', "max_periods_day" integer NOT NULL DEFAULT '6', "max_periods_week" integer NOT NULL DEFAULT '30', "status" character varying(20) NOT NULL DEFAULT 'active', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "is_class_teacher" boolean NOT NULL DEFAULT false, "class_teacher_class_id" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1882c07aedb478aca672340c82a" UNIQUE ("employee_code"), CONSTRAINT "UQ_7568c49a630907119e4a665c605" UNIQUE ("email"), CONSTRAINT "PK_a8d4f83be3abe4c687b0a0093c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" character varying(20) NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(20) NOT NULL, "periods_per_week" integer NOT NULL, "is_elective" boolean NOT NULL DEFAULT false, "difficulty" integer NOT NULL DEFAULT '5', "grade_level" text array NOT NULL DEFAULT '{}', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" character varying(20) NOT NULL, "name" character varying(50) NOT NULL, "sections" text array NOT NULL DEFAULT '{}', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" character varying(20) NOT NULL, "name" character varying(100) NOT NULL, "type" character varying(30) NOT NULL DEFAULT 'classroom', "capacity" integer NOT NULL DEFAULT '30', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sections" ("id" character varying(40) NOT NULL, "class_id" character varying(20) NOT NULL, "name" character varying(10) NOT NULL, "class_teacher_id" character varying(20), "room_id" character varying(20), "capacity" integer NOT NULL DEFAULT '40', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_section_class_name" UNIQUE ("class_id", "name"), CONSTRAINT "PK_f9749dd3bffd880a497d007e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "periods" ("id" character varying(20) NOT NULL, "number" integer NOT NULL, "start_time" character varying(10) NOT NULL, "end_time" character varying(10) NOT NULL, "is_break" boolean NOT NULL DEFAULT false, "label" character varying(50) NOT NULL, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86c6afb6c818d97dc321898627c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "academic_year_id" integer, "title" character varying(255) NOT NULL, "description" text, "created_by" character varying NOT NULL, "created_by_name" character varying(255), "status" character varying NOT NULL DEFAULT 'pending', "priority" character varying(20) NOT NULL DEFAULT 'medium', "start_date" date, "due_date" TIMESTAMP WITH TIME ZONE, "remarks" text, "assigned_to" text array NOT NULL DEFAULT '{}', "file_url" text, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" character varying NOT NULL, "teacher_id" character varying(20) NOT NULL, "status" character varying NOT NULL DEFAULT 'not_started', "escalated" boolean NOT NULL DEFAULT false, "escalation_count" integer NOT NULL DEFAULT '0', "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b68f42cf36d807d8a19a96066d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leave_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "academic_year_id" integer, "leave_duration" character varying(20) NOT NULL DEFAULT 'FULL_DAY', "deducted_leaves" numeric(4,1) NOT NULL DEFAULT '1', "teacher_id" character varying(50), "student_id" character varying(10), "leave_owner_type" character varying(10) NOT NULL DEFAULT 'teacher', "leave_type" character varying(20) NOT NULL DEFAULT 'other', "start_date" date NOT NULL, "end_date" date NOT NULL, "reason" text, "status" character varying NOT NULL DEFAULT 'pending', "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "approved_at" TIMESTAMP WITH TIME ZONE, "approved_by" character varying, "remarks" text, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "proxy_assigned" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d986913818cf9a2943d0dbe8f56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proxy_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "leave_application_id" character varying, "original_teacher_id" character varying(50), "proxy_teacher_id" character varying(50), "class_id" character varying(20) NOT NULL, "subject_id" character varying(20) NOT NULL, "date" date NOT NULL, "period_id" character varying(20), "status" character varying NOT NULL DEFAULT 'pending', "approved_at" TIMESTAMP WITH TIME ZONE, "approved_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2ae21510e7d7d81eda68b1466fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timetables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "academic_year_id" integer, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "grids" jsonb, "published_at" TIMESTAMP WITH TIME ZONE, "effective_from" date, "effective_to" date, "published_by" character varying, "class_id" character varying, "status" character varying(20) NOT NULL DEFAULT 'draft', "is_active" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9dd7e50645bff59e9ac5b4725c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timetable_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "school_id" character varying(50) NOT NULL, "period_slots" jsonb NOT NULL DEFAULT '[]', "working_days" text array NOT NULL DEFAULT '{}', "rules" jsonb NOT NULL DEFAULT '{}', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e51acb457958c3f13af091b4675" UNIQUE ("school_id"), CONSTRAINT "PK_577d64d1b6d6c37e6daa3d3647d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_records_status_enum" AS ENUM('present', 'absent', 'leave')`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" character varying(50) NOT NULL, "class_id" character varying(50) NOT NULL, "section" character varying(10), "date" date NOT NULL, "status" "public"."attendance_records_status_enum" NOT NULL DEFAULT 'present', "remarks" text, "marked_by_teacher_id" character varying(50), "subject_id" character varying(50), "period_id" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fa3f22fca80ff41e0d318923ea3" UNIQUE ("student_id", "date"), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dbace05c012526710663f8d891" ON "attendance_records" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc48ccbd03396874857ab06ac3" ON "attendance_records" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fb6ef15f899489af7e47b6c83" ON "attendance_records" ("date") `);
        await queryRunner.query(`CREATE TABLE "fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "student_id" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "due_date" date NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'pending', "description" character varying(255), "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_97f3a1b1b8ee5674fd4da93f461" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "academic_year_id" integer, "title" character varying(255) NOT NULL, "type" character varying(50), "data" jsonb, "created_by" character varying NOT NULL, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "type" character varying NOT NULL DEFAULT 'task', "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "academic_years" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "is_active" boolean NOT NULL DEFAULT false, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_645d0f115fa85aaecffdc11cbaa" UNIQUE ("name"), CONSTRAINT "PK_2021b90bfbfa6c9da7df34ca1cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teacher_leave_balances" ("id" SERIAL NOT NULL, "teacher_id" character varying(50) NOT NULL, "academic_year_id" integer NOT NULL, "total_leaves" numeric(5,1) NOT NULL DEFAULT '20', "used_leaves" numeric(5,1) NOT NULL DEFAULT '0', "remaining_leaves" numeric(5,1) NOT NULL DEFAULT '20', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d10af2b59a563eb94c7318c89b0" UNIQUE ("teacher_id", "academic_year_id"), CONSTRAINT "PK_08bf8eed3880ba6be927d5bf8ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "message" text NOT NULL, "type" character varying NOT NULL DEFAULT 'general', "rating" integer, "principal_id" uuid NOT NULL, "teacher_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8389f9e087a57689cd5be8b2b13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" character varying(5) NOT NULL, "fullName" character varying(255) NOT NULL, "email" character varying(255), "passwordHash" character varying NOT NULL, "className" character varying(100) NOT NULL, "section" character varying(10) NOT NULL, "section_id" character varying(40), "refresh_token_hash" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9d9f010d4d6a6eea8b4779638c4" UNIQUE ("studentId"), CONSTRAINT "UQ_25985d58c714a4a427ced57507b" UNIQUE ("email"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "circulars" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text NOT NULL, "category" character varying NOT NULL DEFAULT 'General', "created_by" uuid NOT NULL, "created_by_role" character varying(50) NOT NULL, "is_published" boolean NOT NULL DEFAULT true, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d5986883d52418ff55d9b5834d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mailbox_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "message" text NOT NULL, "sender_name" character varying(255) NOT NULL, "sender_role" character varying(50) NOT NULL, "category" character varying NOT NULL DEFAULT 'General', "is_published" boolean NOT NULL DEFAULT true, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_865e565d761179ce3e394b8b619" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text NOT NULL, "category" character varying(100) NOT NULL, "level" character varying(100), "badge" character varying(100), "awarded_on" date, "student_id" character varying(50) NOT NULL, "student_ref_id" character varying(20), "student_name" character varying(255) NOT NULL, "class_name" character varying(100), "created_by" character varying(50), "created_by_role" character varying(50), "featured" boolean NOT NULL DEFAULT false, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bc19c37c6249f70186f318d71d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "sender_id" character varying(50) NOT NULL, "sender_role" character varying(20) NOT NULL, "sender_name" character varying(255) NOT NULL, "receiver_id" character varying(50) NOT NULL, "receiver_role" character varying(20) NOT NULL, "receiver_name" character varying(255) NOT NULL, "subject" character varying(255) NOT NULL, "message" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "deleted_by_sender" boolean NOT NULL DEFAULT false, "deleted_by_receiver" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "homework" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text NOT NULL, "topic" character varying(255), "priority" character varying(20) NOT NULL DEFAULT 'medium', "submission_type" character varying(10) NOT NULL, "class_id" character varying(20) NOT NULL, "class_name" character varying(100) NOT NULL, "subject_id" character varying(20) NOT NULL, "subject_name" character varying(100) NOT NULL, "teacher_id" character varying(20) NOT NULL, "teacher_name" character varying(255) NOT NULL, "academic_year_id" integer NOT NULL, "attachment_url" text, "attachment_name" character varying, "attachment_mime_type" character varying, "attachment_size" integer, "status" character varying(20) NOT NULL DEFAULT 'published', "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90dbf463ef94040ed137c4fd38d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f17cbe8bf30586be3044a515e" ON "homework" ("class_id", "subject_id", "academic_year_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e85813c4d383eca4ce4c689a9" ON "homework" ("teacher_id", "academic_year_id") `);
        await queryRunner.query(`CREATE TABLE "homework_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "homework_id" uuid NOT NULL, "section" character varying(10) NOT NULL, "deadline" TIMESTAMP WITH TIME ZONE NOT NULL, "published_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'published', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_26f75ad244f07a4cb7fd87115c0" UNIQUE ("homework_id", "section"), CONSTRAINT "PK_6e96c9e0467aa788a4ce9c81ac5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09acc0227dc8b257606b8b4eb4" ON "homework_assignments" ("homework_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b38d74a247e02df0914f5586b6" ON "homework_assignments" ("section", "deadline") `);
        await queryRunner.query(`CREATE TABLE "homework_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "homework_assignment_id" uuid NOT NULL, "student_id" uuid NOT NULL, "submission_text" text, "file_url" text, "file_name" character varying, "file_mime_type" character varying, "file_size" integer, "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "submission_version" integer NOT NULL DEFAULT '1', "status" character varying(20) NOT NULL DEFAULT 'submitted', "marks_obtained" numeric(6,2), "teacher_feedback" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c100251dd6184d4ddaf1982ad6c" UNIQUE ("homework_assignment_id", "student_id"), CONSTRAINT "PK_4c570ffb4ce1a34b63afa9d1b26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3b2235f48ab8488a9e964c0172" ON "homework_submissions" ("student_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2c5cfd2ad5e3a2c070577a70b" ON "homework_submissions" ("homework_assignment_id") `);
        await queryRunner.query(`CREATE TABLE "teaching_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teacher_id" character varying(20) NOT NULL, "class_id" character varying(20) NOT NULL, "section" character varying(10) NOT NULL, "subject_id" character varying(20) NOT NULL, "academic_year_id" integer NOT NULL, "school_id" character varying(50) NOT NULL DEFAULT 'school_001', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae367d2dbacbc21d9bb785de4cb" UNIQUE ("teacher_id", "class_id", "section", "subject_id", "academic_year_id"), CONSTRAINT "PK_baf0d10098561a9840957b512e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6b54511fb475e89f52e8f2c246" ON "teaching_assignments" ("teacher_id", "academic_year_id", "is_active") `);
        await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_4d8b425eabbf542265e620d6111" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_27db91d7369af6f181412afa99f" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_9e40f861d3aaf51ea6e9ba4b76d" FOREIGN KEY ("class_teacher_id") REFERENCES "teachers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_8cb4031f7556945bc3e155f57ff" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_d849a6bd5722670e6e182f7d00c" FOREIGN KEY ("principal_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_bb612409cbb5c4563d2dad30ade" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_bb612409cbb5c4563d2dad30ade"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_d849a6bd5722670e6e182f7d00c"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_8cb4031f7556945bc3e155f57ff"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_9e40f861d3aaf51ea6e9ba4b76d"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_27db91d7369af6f181412afa99f"`);
        await queryRunner.query(`ALTER TABLE "teachers" DROP CONSTRAINT "FK_4d8b425eabbf542265e620d6111"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b54511fb475e89f52e8f2c246"`);
        await queryRunner.query(`DROP TABLE "teaching_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2c5cfd2ad5e3a2c070577a70b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b2235f48ab8488a9e964c0172"`);
        await queryRunner.query(`DROP TABLE "homework_submissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b38d74a247e02df0914f5586b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09acc0227dc8b257606b8b4eb4"`);
        await queryRunner.query(`DROP TABLE "homework_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e85813c4d383eca4ce4c689a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f17cbe8bf30586be3044a515e"`);
        await queryRunner.query(`DROP TABLE "homework"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "achievements"`);
        await queryRunner.query(`DROP TABLE "mailbox_messages"`);
        await queryRunner.query(`DROP TABLE "circulars"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TABLE "feedback"`);
        await queryRunner.query(`DROP TABLE "teacher_leave_balances"`);
        await queryRunner.query(`DROP TABLE "academic_years"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TABLE "fees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fb6ef15f899489af7e47b6c83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc48ccbd03396874857ab06ac3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbace05c012526710663f8d891"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_records_status_enum"`);
        await queryRunner.query(`DROP TABLE "timetable_settings"`);
        await queryRunner.query(`DROP TABLE "timetables"`);
        await queryRunner.query(`DROP TABLE "proxy_assignments"`);
        await queryRunner.query(`DROP TABLE "leave_applications"`);
        await queryRunner.query(`DROP TABLE "task_assignments"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TABLE "periods"`);
        await queryRunner.query(`DROP TABLE "sections"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`DROP TABLE "teachers"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
