import React, { useEffect, useState } from 'react';

import { useAuth } from '@/core/context/AuthContext';

import { homeworkService } from '../services/homeworkService';

export default function HomeworkMonitoringPage() {
  const { role } = useAuth(); const [items, setItems] = useState([]); const [filters, setFilters] = useState({ classId: '', subjectId: '', teacherId: '', status: '' }); const [error, setError] = useState('');
  const load = async () => { try { const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)).toString(); setItems(await homeworkService.monitor(query ? `?${query}` : '')); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, []);
  const update = (key, value) => setFilters((previous) => ({ ...previous, [key]: value }));
  const archive = async (id, status) => { try { await homeworkService.updateStatus(id, status); await load(); } catch (err) { setError(err.message); } };
  return <div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-2xl font-bold">Homework monitor</h1><p className="text-sm text-gray-500">Read-only operational visibility across classes and sections.</p></div>{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={(event) => { event.preventDefault(); load(); }} className="flex flex-wrap gap-2 rounded-xl border bg-white p-4"><input value={filters.classId} onChange={(event) => update('classId', event.target.value)} placeholder="Class ID" className="rounded border p-2 text-sm" /><input value={filters.subjectId} onChange={(event) => update('subjectId', event.target.value)} placeholder="Subject ID" className="rounded border p-2 text-sm" /><input value={filters.teacherId} onChange={(event) => update('teacherId', event.target.value)} placeholder="Teacher ID" className="rounded border p-2 text-sm" /><select value={filters.status} onChange={(event) => update('status', event.target.value)} className="rounded border p-2 text-sm"><option value="">All statuses</option><option value="published">Published</option><option value="archived">Archived</option><option value="cancelled">Cancelled</option></select><button className="rounded bg-blue-600 px-3 py-2 text-sm text-white">Apply</button></form><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-gray-500"><tr><th className="p-4">Homework</th><th className="p-4">Class / section</th><th className="p-4">Teacher</th><th className="p-4">Submissions</th>{role === 'admin' && <th className="p-4" />}</tr></thead><tbody>{!items.length ? <tr><td className="p-8 text-center text-gray-500" colSpan={5}>No homework found.</td></tr> : items.map((item) => <tr key={item.id} className="border-t"><td className="p-4"><div className="font-medium">{item.title}</div><div className="text-xs text-gray-500">{item.subjectName} · {item.status}</div></td><td className="p-4">{item.className} · {item.assignments.map((assignment) => assignment.section).join(', ') || '—'}</td><td className="p-4">{item.teacherName}</td><td className="p-4">{item.submissionCount} submitted / {item.reviewedCount} reviewed</td>{role === 'admin' && <td className="p-4 text-right">{item.status === 'published' && <><button onClick={() => archive(item.id, 'archived')} className="mr-2 text-amber-700">Archive</button><button onClick={() => archive(item.id, 'cancelled')} className="text-red-600">Cancel</button></>}</td>}</tr>)}</tbody></table></div></div>;
}
