import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';

import HomeworkAttachmentInput from '../components/HomeworkAttachmentInput';
import { homeworkService } from '../services/homeworkService';

export default function StudentHomeworkDetailPage() {
  const { assignmentId } = useParams(); const [item, setItem] = useState(null); const [text, setText] = useState(''); const [file, setFile] = useState(null); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { try { const result = await homeworkService.getStudentAssignment(assignmentId); setItem(result); setText(result.submission?.submissionText || ''); } catch (err) { setMessage(err.message); } };
  useEffect(() => { load(); }, [assignmentId]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const data = new FormData(); if (text) data.append('submissionText', text); if (file) data.append('file', file); await homeworkService.submitHomework(assignmentId, data); setMessage('Homework submitted successfully.'); setFile(null); await load(); } catch (err) { setMessage(err.message); } finally { setSaving(false); } };
  if (!item) return <p className="p-6 text-gray-500">Loading homework…</p>;
  const { homework, assignment, submission } = item; const wantsText = homework.submissionType !== 'file'; const wantsFile = homework.submissionType !== 'text';
  return <div className="mx-auto max-w-3xl space-y-5"><Link to="/student/homework" className="text-sm text-blue-600">← Homework</Link>{message && <p className={`rounded p-3 text-sm ${message.includes('successfully') ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}>{message}</p>}<section className="rounded-xl border bg-white p-6"><h1 className="text-2xl font-bold">{homework.title}</h1><p className="mt-1 text-sm text-gray-500">{homework.subjectName} · {homework.teacherName} · {homework.priority} priority</p><p className="mt-4 whitespace-pre-wrap">{homework.description}</p><p className="mt-3 text-sm font-medium">Deadline: {new Date(assignment.deadline).toLocaleString()}</p>{homework.attachmentUrl && <a href={homework.attachmentUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm text-blue-600">Open teacher attachment</a>}</section><section className="rounded-xl border bg-white p-6"><h2 className="font-bold">Your submission</h2>{!item.isSubmissionOpen ? <p className="mt-3 rounded bg-red-50 p-3 text-sm text-red-700">Deadline passed. Submission is closed.</p> : <form onSubmit={submit} className="mt-4 space-y-4">{wantsText && <label className="block text-sm font-medium">Text answer<textarea value={text} onChange={(event) => setText(event.target.value)} rows={5} className="mt-1 w-full rounded border p-2" /></label>}{wantsFile && <HomeworkAttachmentInput file={file} onChange={setFile} label={homework.submissionType === 'file' ? 'File upload' : 'File upload (optional)'} />}<button disabled={saving} className="rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Submitting…' : submission ? 'Resubmit homework' : 'Submit homework'}</button></form>}{submission?.teacherFeedback && <p className="mt-4 rounded bg-blue-50 p-3 text-sm">Teacher feedback: {submission.teacherFeedback}</p>}</section></div>;
}
