import React, { useEffect, useState } from 'react';

import { apiRequest } from '@/core/api/client';

import { homeworkService } from '../services/homeworkService';

export default function TeachingAssignmentsPage() {
  const [items, setItems] = useState([]); const [teachers, setTeachers] = useState([]); const [classes, setClasses] = useState([]); const [subjects, setSubjects] = useState([]); const [years, setYears] = useState([]); const [message, setMessage] = useState(''); const [form, setForm] = useState({ teacherId: '', classId: '', section: '', subjectId: '', academicYearId: '' });
  const load = async () => { try { const [assignments, teacherData, classData, subjectData, yearData] = await Promise.all([homeworkService.getTeachingAssignments(), apiRequest('/teachers'), apiRequest('/classes'), apiRequest('/subjects'), apiRequest('/academic-years')]); setItems(assignments); setTeachers(teacherData); setClasses(classData); setSubjects(subjectData); setYears(yearData); const active = yearData.find((year) => year.isActive); if (active) setForm((previous) => ({ ...previous, academicYearId: previous.academicYearId || String(active.id) })); } catch (err) { setMessage(err.message); } };
  useEffect(() => { load(); }, []);
  const selectedClass = classes.find((item) => item.id === form.classId); const update = (key, value) => setForm((previous) => ({ ...previous, [key]: value }));
  const submit = async (event) => { event.preventDefault(); try { await homeworkService.createTeachingAssignment({ ...form, academicYearId: Number(form.academicYearId) }); setMessage('Teaching assignment created.'); setForm((previous) => ({ ...previous, section: '' })); await load(); } catch (err) { setMessage(err.message); } };
  const toggle = async (item) => { try { await homeworkService.updateTeachingAssignment(item.id, { isActive: !item.isActive }); await load(); } catch (err) { setMessage(err.message); } };
  return <div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-2xl font-bold">Teaching assignments</h1><p className="text-sm text-gray-500">The authorization source for teacher homework publishing.</p></div>{message && <p className="rounded bg-blue-50 p-3 text-sm text-blue-700">{message}</p>}<form onSubmit={submit} className="grid grid-cols-1 gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><select required value={form.teacherId} onChange={(event) => update('teacherId', event.target.value)} className="rounded border p-2"><option value="">Teacher</option>{teachers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required value={form.classId} onChange={(event) => { update('classId', event.target.value); update('section', ''); }} className="rounded border p-2"><option value="">Class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required value={form.section} onChange={(event) => update('section', event.target.value)} className="rounded border p-2"><option value="">Section</option>{(selectedClass?.sections || []).map((section) => <option key={section} value={section}>{section}</option>)}</select><select required value={form.subjectId} onChange={(event) => update('subjectId', event.target.value)} className="rounded border p-2"><option value="">Subject</option>{subjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required value={form.academicYearId} onChange={(event) => update('academicYearId', event.target.value)} className="rounded border p-2"><option value="">Academic year</option>{years.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="rounded bg-blue-600 px-4 py-2 font-medium text-white">Add assignment</button></form><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-gray-500"><tr><th className="p-3">Teacher ID</th><th className="p-3">Class / section</th><th className="p-3">Subject</th><th className="p-3">Year</th><th className="p-3">Status</th><th className="p-3" /></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t"><td className="p-3">{item.teacherId}</td><td className="p-3">{item.classId} / {item.section}</td><td className="p-3">{item.subjectId}</td><td className="p-3">{item.academicYearId}</td><td className="p-3">{item.isActive ? 'Active' : 'Inactive'}</td><td className="p-3 text-right"><button onClick={() => toggle(item)} className="text-blue-600">{item.isActive ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div></div>;
}
