import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';

import HomeworkReviewDialog from '../components/HomeworkReviewDialog';
import HomeworkSubmissionTable from '../components/HomeworkSubmissionTable';
import SectionMultiSelect from '../components/SectionMultiSelect';
import { homeworkService } from '../services/homeworkService';

export default function TeacherHomeworkDetailPage() {
  const { homeworkId } = useParams(); const [detail, setDetail] = useState(null); const [context, setContext] = useState([]); const [selectedAssignment, setAssignment] = useState(null); const [submissions, setSubmissions] = useState([]); const [reviewing, setReviewing] = useState(null); const [sections, setSections] = useState([]); const [deadline, setDeadline] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { try { const [record, options] = await Promise.all([homeworkService.getHomework(homeworkId), homeworkService.getTeacherContext()]); setDetail(record); setContext(options); } catch (err) { setMessage(err.message); } };
  useEffect(() => { load(); }, [homeworkId]);
  const viewSubmissions = async (assignment) => { setAssignment(assignment); try { setSubmissions(await homeworkService.getAssignmentSubmissions(assignment.id)); } catch (err) { setMessage(err.message); } };
  const addSections = async (event) => { event.preventDefault(); try { await homeworkService.addAssignments(homeworkId, { sectionIds: sections, deadline: new Date(deadline).toISOString() }); setSections([]); setDeadline(''); await load(); } catch (err) { setMessage(err.message); } };
  const saveReview = async (data) => { try { await homeworkService.reviewSubmission(reviewing.id, data); setReviewing(null); await viewSubmissions(selectedAssignment); } catch (err) { setMessage(err.message); } };
  if (!detail) return <p className="p-6 text-gray-500">Loading homework…</p>;
  const allowed = context.filter((item) => item.classId === detail.classId && item.subjectId === detail.subjectId).map((item) => item.section).filter((section) => !detail.assignments.some((item) => item.section === section));
  return <div className="mx-auto max-w-6xl space-y-6"><Link to="/homework" className="text-sm text-blue-600">← Homework</Link>{message && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{message}</p>}<section className="rounded-xl border border-gray-200 bg-white p-6"><h1 className="text-2xl font-bold">{detail.title}</h1><p className="mt-1 text-gray-600">{detail.subjectName} · {detail.className} · {detail.topic || 'No topic'}</p><p className="mt-4 whitespace-pre-wrap text-sm">{detail.description}</p>{detail.attachmentUrl && <a href={detail.attachmentUrl} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm text-blue-600">Open attachment</a>}</section><section className="rounded-xl border border-gray-200 bg-white p-6"><h2 className="font-bold">Assign to another section</h2>{allowed.length ? <form onSubmit={addSections} className="mt-4 space-y-3"><SectionMultiSelect sections={allowed} value={sections} onChange={setSections} /><input required type="datetime-local" value={deadline} onChange={(event) => setDeadline(event.target.value)} className="rounded border p-2" /><button disabled={!sections.length} className="ml-2 rounded bg-blue-600 px-3 py-2 text-sm text-white disabled:opacity-50">Assign sections</button></form> : <p className="mt-2 text-sm text-gray-500">No additional assigned sections are available.</p>}</section><section className="rounded-xl border border-gray-200 bg-white p-6"><h2 className="font-bold">Sections and submissions</h2><div className="mt-4 flex flex-wrap gap-2">{detail.assignments.map((assignment) => <button key={assignment.id} onClick={() => viewSubmissions(assignment)} className={`rounded border px-3 py-2 text-sm ${selectedAssignment?.id === assignment.id ? 'border-blue-600 bg-blue-50 text-blue-700' : 'border-gray-200'}`}>Section {assignment.section} · {new Date(assignment.deadline).toLocaleString()}</button>)}</div>{selectedAssignment && <div className="mt-5"><HomeworkSubmissionTable submissions={submissions} onReview={setReviewing} /></div>}</section><HomeworkReviewDialog submission={reviewing} onClose={() => setReviewing(null)} onSave={saveReview} /></div>;
}
