import { BookOpen, Plus, X } from 'lucide-react';
import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';

import { SectionHeader } from '@/core/components/SectionHeader';

import HomeworkForm from '../components/HomeworkForm';
import { homeworkService } from '../services/homeworkService';

export default function TeacherHomeworkPage() {
  const [homework, setHomework] = useState([]); const [context, setContext] = useState([]); const [modal, setModal] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [query, setQuery] = useState('');
  const load = async () => { setLoading(true); try { const [list, options] = await Promise.all([homeworkService.getTeacherHomework(), homeworkService.getTeacherContext()]); setHomework(list); setContext(options); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const rows = useMemo(() => homework.filter((item) => `${item.title} ${item.subjectName} ${item.className}`.toLowerCase().includes(query.toLowerCase())), [homework, query]);
  const publish = async (data) => { setSaving(true); setError(''); try { await homeworkService.createHomework(data); setModal(false); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-6xl space-y-6"><SectionHeader title="Homework" description="Publish and review homework for your assigned sections" action={<button onClick={() => setModal(true)} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white"><Plus size={16} />Publish homework</button>} />{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search homework…" className="w-full max-w-md rounded-lg border border-gray-200 p-2" /><div className="overflow-hidden rounded-xl border border-gray-200 bg-white">{loading ? <p className="p-8 text-center text-gray-500">Loading homework…</p> : !rows.length ? <p className="p-8 text-center text-gray-500">No homework published yet.</p> : <table className="w-full text-sm"><thead className="bg-gray-50 text-left text-gray-500"><tr><th className="p-4">Homework</th><th className="p-4">Class</th><th className="p-4">Sections</th><th className="p-4">Deadlines</th><th className="p-4" /></tr></thead><tbody>{rows.map((item) => <tr key={item.id} className="border-t"><td className="p-4"><div className="flex gap-2 font-medium"><BookOpen size={16} className="text-blue-600" />{item.title}</div><div className="mt-1 text-xs text-gray-500">{item.subjectName} · {item.topic || 'No topic'}</div></td><td className="p-4">{item.className}</td><td className="p-4">{item.assignments.map((assignment) => assignment.section).join(', ')}</td><td className="p-4 text-xs">{item.assignments.map((assignment) => <div key={assignment.id}>{assignment.section}: {new Date(assignment.deadline).toLocaleString()}</div>)}</td><td className="p-4 text-right"><Link to={`/homework/${item.id}`} className="font-medium text-blue-600">Open</Link></td></tr>)}</tbody></table>}</div>{modal && <div className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-4"><div className="mx-auto mt-8 w-full max-w-3xl rounded-xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-lg font-bold">Publish homework</h2><button onClick={() => setModal(false)}><X /></button></div><HomeworkForm context={context} onSubmit={publish} submitting={saving} /></div></div>}</div>;
}
